version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Backend API Setup
          command: |
            npm run api-install
      - run:
          name: Backend API Build
          command: |
            npm run api-build
      - run:
          name: Backend API Deploy
          command: |
            npm run api-deploy
      - run:
          name: Frontend API Setup
          command: |
            npm run frontend-install
      - run:
          name: Frontend API Build
          command: |
            npm run frontend-build
      - run:
          name: Frontend API Deploy
          command: |
            npm run frontend-deploy

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main